import { spawn } from 'node:child_process';
import { mkdtemp, cp, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { createServer } from 'node:net';
import { resolve, join } from 'node:path';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';
import { unzipSync, zipSync, strFromU8, strToU8 } from 'fflate';
import * as XLSX from 'xlsx';
const delay = ms => new Promise(r => setTimeout(r, ms));
const root = await mkdtemp(join(tmpdir(), 'wmps-desktop-'));
const workspace = join(root, 'Q3 Planning');
await cp(resolve('examples/Q3 Planning'), workspace, { recursive: true });
const port = await new Promise(r => { const s = createServer(); s.listen(0, '127.0.0.1', () => { const p = s.address().port; s.close(() => r(p)); }); });
const paths = ['README.md', 'docs/Proposal.docx', 'data/Budget.xlsx', 'legal/Reference.pdf'].map(p => join(workspace, p));
// Exercise a real OOXML comment and its body anchor without changing the example.
const archive = unzipSync(await readFile(paths[1]));
let documentXml = strFromU8(archive['word/document.xml']);
documentXml = documentXml.replace('<w:r>', '<w:commentRangeStart w:id="42"/><w:r>').replace('</w:p>', '<w:commentRangeEnd w:id="42"/><w:r><w:commentReference w:id="42"/></w:r></w:p>');
archive['word/document.xml'] = strToU8(documentXml);
archive['word/comments.xml'] = strToU8('<?xml version="1.0"?><w:comments xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:comment w:id="42" w:author="Alex Chen" w:initials="AC" w:date="2026-09-23T08:00:00Z"><w:p><w:r><w:t>Please clarify the beta timeline.</w:t></w:r></w:p></w:comment></w:comments>');
archive['word/_rels/document.xml.rels'] = strToU8(strFromU8(archive['word/_rels/document.xml.rels']).replace('</Relationships>', '<Relationship Id="rIdTestComment" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="comments.xml"/></Relationships>'));
archive['[Content_Types].xml'] = strToU8(strFromU8(archive['[Content_Types].xml']).replace('</Types>', '<Override PartName="/word/comments.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml"/></Types>'));
await writeFile(paths[1], zipSync(archive));
const proc = spawn(process.env.WMPS_APP_BINARY || resolve('node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'), [`--remote-debugging-port=${port}`, ...(process.env.WMPS_APP_BINARY ? [] : ['.'])], { env: { ...process.env, WMPS_USER_DATA: join(root, 'state'), WMPS_TEST_WORKSPACE: workspace, WMPS_TEST_TABS: paths.join(',') }, stdio: ['ignore', 'ignore', 'pipe'] });
let stderr = ''; proc.stderr.on('data', b => stderr += b); let socket;
try {
  let target;
  for (let i = 0; i < 100; i++) { try { target = (await fetch(`http://127.0.0.1:${port}/json`).then(r => r.json())).find(t => t.type === 'page'); if (target) break; } catch {} await delay(100); }
  assert(target, stderr); socket = new WebSocket(target.webSocketDebuggerUrl); await new Promise(r => socket.addEventListener('open', r, { once: true })); let sequence = 0; const pending = new Map();
  socket.addEventListener('message', event => { const m = JSON.parse(event.data); if (pending.has(m.id)) { const p = pending.get(m.id); pending.delete(m.id); m.error ? p.reject(m.error) : p.resolve(m.result); } });
  const call = (method, params = {}) => new Promise((resolve, reject) => { const id = ++sequence; pending.set(id, { resolve, reject }); socket.send(JSON.stringify({ id, method, params })); });
  const evaluate = async expression => { const r = await call('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error(JSON.stringify(r.exceptionDetails)); return r.result.value; };
  const wait = async expression => { for (let i = 0; i < 150; i++) { if (await evaluate(`Boolean(${expression})`)) return; await delay(100); } throw new Error('Timed out: ' + expression + '\n' + await evaluate('document.body.innerText')); };
  const screenshot = async name => { await mkdir('artifacts', { recursive: true }); const { data } = await call('Page.captureScreenshot', { format: 'png' }); await writeFile(`artifacts/${name}.png`, Buffer.from(data, 'base64')); };
  const tab = async name => { await evaluate(`[...document.querySelectorAll('.document-tab')].find(e=>e.textContent.includes(${JSON.stringify(name)})).click()`); await delay(300); };
  await wait("document.querySelector('.markdown-preview')?.textContent.includes('Q3 Planning')");
  await evaluate("window.wmps.setTheme('light')"); await delay(300); await screenshot('markdown-light');
  await evaluate("document.querySelector('.cm-content').focus()"); await call('Input.insertText', { text: 'PERSISTED EDIT ' }); await wait("document.querySelector('.dirty-dot')");
  await tab('Proposal.docx'); await wait("document.querySelector('.docx-editor')"); await delay(1500); await screenshot('word-light');
  await wait("document.querySelector('.word-comments')?.textContent.includes('Please clarify the beta timeline.')");
  assert(await evaluate("document.querySelector('.word-comments').textContent.includes('Alex Chen')"));
  const wordPoint = await evaluate("(() => { const r=document.querySelector('.docx-pages').getBoundingClientRect(); return {x:r.x+180,y:r.y+112}; })()");
  await call('Input.dispatchMouseEvent', {type:'mousePressed',...wordPoint,button:'left',clickCount:1});
  await call('Input.dispatchMouseEvent', {type:'mouseReleased',...wordPoint,button:'left',clickCount:1});
  await call('Input.insertText', {text:'VERIFIED WORD '});
  await wait("document.querySelector('.document-tab.active .dirty-dot')");
  await tab('README.md'); assert(await evaluate("document.querySelector('.cm-content').textContent.includes('PERSISTED EDIT')"), 'Switching tabs lost Markdown edits');
  await evaluate(`document.querySelector('[aria-label="Save document"]').click()`); await wait("!document.querySelector('.document-tab.active .dirty-dot')"); assert((await readFile(paths[0], 'utf8')).includes('PERSISTED EDIT'));
  await tab('Budget.xlsx'); await wait("document.querySelector('.univer-host canvas')"); await delay(900); await screenshot('spreadsheet-light');
  await evaluate("(() => {const input=[...document.querySelectorAll('.univer-host input')].find(e=>e.value==='A1'); input.focus();input.select();})()");
  await call('Input.insertText',{text:'B2'});
  await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});
  await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});
  await delay(200);
  await call('Input.dispatchKeyEvent',{type:'keyDown',key:'9',code:'Digit9',text:'9',windowsVirtualKeyCode:57});
  await call('Input.dispatchKeyEvent',{type:'keyUp',key:'9',code:'Digit9',windowsVirtualKeyCode:57});
  await call('Input.insertText',{text:'0000'});
  await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});
  await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});
  await wait("document.querySelector('.document-tab.active .dirty-dot')");
  await tab('Reference.pdf'); await wait("document.querySelector('.pdf-page canvas')?.width > 0"); await screenshot('pdf-light');
  await tab('Budget.xlsx'); await evaluate(`document.querySelector('[aria-label="Save document"]').click()`); await wait("!document.querySelector('.document-tab.active .dirty-dot')");
  assert.equal(XLSX.read(await readFile(paths[2])).Sheets.Budget.B2.v,90000,'Spreadsheet edits must survive switching tabs and save');
  await tab('Proposal.docx'); await evaluate(`document.querySelector('[aria-label="Save document"]').click()`); await wait("!document.querySelector('.document-tab.active .dirty-dot')");
  assert(strFromU8(unzipSync(await readFile(paths[1]))['word/document.xml']).includes('VERIFIED WORD'),'DOCX edits must survive switching tabs and save');
  assert(strFromU8(unzipSync(await readFile(paths[1]))['word/document.xml']).includes('commentRangeStart'), 'Saving must preserve comment anchors');
  assert(strFromU8(unzipSync(await readFile(paths[1]))['word/comments.xml']).includes('Please clarify the beta timeline.'),'Saving must preserve comments');
  await tab('README.md'); await evaluate(`document.querySelector('[aria-label="Toggle theme"]').click()`); await wait("matchMedia('(prefers-color-scheme: dark)').matches"); await screenshot('markdown-dark');
  await tab('Budget.xlsx'); await screenshot('spreadsheet-dark');
  await evaluate(`document.querySelector('[aria-label="Search workspace"]').click()`);
  await wait("document.querySelector('.workspace-search-input input')");
  const searchBounds = await evaluate("document.querySelector('.search-panel').getBoundingClientRect().toJSON()");
  assert(searchBounds.top >= 44 && searchBounds.left >= 44, 'Search must stay below the titlebar and beside the activity rail');
  await call('Input.insertText', {text:'Q3'});
  await wait("document.querySelector('.search-results button')"); await screenshot('search-dark');
  await evaluate(`document.querySelector('[aria-label="Close search"]').click()`);
  await tab('Proposal.docx'); await screenshot('word-dark');
  await evaluate(`document.querySelector('[aria-label="New Markdown document"]').click()`); await wait("document.querySelector('#document-name')"); await evaluate("document.querySelector('.name-dialog').requestSubmit()"); await wait("document.querySelector('.document-tab.active')?.textContent.includes('Untitled.md')"); assert((await readFile(join(workspace, 'Untitled.md'), 'utf8')).includes('# Untitled'));
  const collision = await evaluate(`window.wmps.createFile(${JSON.stringify(paths[0])},new Uint8Array([1])).then(()=>false,()=>true)`); assert(collision, 'Create must not overwrite an existing document');
  assert((await readFile(paths[0], 'utf8')).includes('PERSISTED EDIT'));
  assert.equal(await evaluate("document.querySelector('.editor-error')?.innerText || document.querySelector('.error-banner')?.innerText || ''"), '');
  console.log(JSON.stringify({ markdownSave: true, tabEditsPreserved: true, wordRendered: true, wordSave: true, wordComments: true, commentPreservation: true, searchPlacement: true, spreadsheetRendered: true, spreadsheetSave: true, pdfRendered: true, lightDark: true, newDocument: true, overwriteProtected: true, screenshots: 'artifacts/' }));
} catch (e) { console.error(stderr.slice(-2000)); throw e; } finally { socket?.close(); const exited = new Promise(r => proc.once('exit', r)); proc.kill('SIGKILL'); await exited; await rm(root, { recursive: true, force: true }); }
